CC = wcc
AS = wasm
LD = wlink
CL = wcl

CFLAGS = -3 -bt=dos
LDFLAGS = SYSTEM DOS

OBJ = main.obj pci.obj isawait.obj

all : ISAWAIT.EXE

ISAWAIT.EXE : $(OBJ)
	$(LD) $(LDFLAGS) NAME ISAWAIT.EXE FILE {$(OBJ)}

.c.obj : .AUTODEPEND
		$(CC) $(CFLAGS) -fo=$@ $<